#!/bin/bash

if [ -d ../sphere_in_a_tube ]; then
   echo Directory sphere_in_a_tube exists
   echo -n "Remove directory? (y or n (=default) ) ? > "
   read input; goahead=${input:=n}
   if [ $goahead = y ] ; then
     rm -r ../sphere_in_a_tube
     mkdir ../sphere_in_a_tube
   else
     echo "Continuing with existing directory"
   fi
else
  mkdir ../sphere_in_a_tube
fi

echo "Copying files"
cp *.f90 *.igo *.txt ../sphere_in_a_tube
cd ..
echo "Creating zip file"
if [ -f project_tfem_saramito.zip ]; then
  rm project_tfem_saramito.zip
fi
zip -r -FS project_tfem_saramito.zip sphere_in_a_tube -x \*.DS_Store
